### ISSUE TITLE
其他部件也需要使用 builder，怎么同时使用呢？

### ISSUE THREAD

**Issue by lonely2099** [kokohuang/flutter_easyloading#73]
感谢作者提供的小部件，

我在使用一个新的小部件时，
https://pub.dev/packages/one_context
这个组建也需要挂到 builder
builder: OneContext().builder,
loading也需要builder
builder: EasyLoading.init(),

请问我该怎么同时处理这两个情况!

**Comment by kokohuang** [comment]
```dart
  /// init EasyLoading
  static TransitionBuilder init({
    TransitionBuilder builder,
  }) {
    return (BuildContext context, Widget child) {
      if (builder != null) {
        return builder(context, FlutterEasyLoading(child: child));
      } else {
        return FlutterEasyLoading(child: child);
      }
    };
  }
```

@lonely2099  试试将 `OneContext().builder` 作为 `builder` 参数传入

**Comment by lonely2099** [comment]
额。。。。怎么看TransitionBuilder都不像一个正常语法的函数呀！莫非dart的新语法么。。。我去试试，非常感谢！

**Comment by lonely2099** [comment]
呀。。。貌似没办法这样使用，我去折腾下看看！成功了回复！

**Comment by v75273278** [comment]
把builder 作为参数传进去  就行
