### ISSUE TITLE
Init Method Does Not exist 

### ISSUE THREAD

**Issue by k1ycee** [kokohuang/flutter_easyloading#74]
**Describe the bug**

The method 'init' isn't defined for the type 'EasyLoading'.
Try correcting the name to the name of an existing method, or defining a method named 'init'.

**Flutter/Dart info**
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/wildone/snap/flutter/common/flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/wildone/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • CPH2015 (mobile) • NNQOS4QOKF8TCUFU • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
please run `flutter doctor` then put it here.

MaterialApp(
          title: 'Title',
          debugShowCheckedModeBanner: false,
          builder: EasyLoading.init(),
          // navigatorKey: locator<NavigationService>().navigationKey,
          // onGenerateRoute: generateRoute,
          theme: ThemeData(
            fontFamily: "Caros",
            primarySwatch: Colors.blue,
            bottomSheetTheme:
                BottomSheetThemeData(backgroundColor: Colors.transparent),
            visualDensity: VisualDensity.adaptivePlatformDensity,
          ),
          home: _localStorage.getSecondaryState().isLoggedIn == false
              ? LandingScreen()
              : TabsContainer(),
         
        ),

**Comment by kokohuang** [comment]
@k1ycee what’s your EasyLoading version
