### ISSUE TITLE
web端加载中跳动

### ISSUE THREAD

**Issue by songsongtao** [kokohuang/flutter_easyloading#75]
**Describe the bug**
asyLoading.show(status: '加载中..');只要内容是中文就会跳动（web端）

**Flutter/Dart info**
环境正常

**Screenshots**
暂无

**Comment by kokohuang** [comment]
![2021-03-19 09-40-08 2021-03-19 09_40_33](https://user-images.githubusercontent.com/8692455/111719613-307efd00-8897-11eb-8655-ec8691fb8d2e.gif)

经测试，没有跳动现象
