### ISSUE TITLE
I can't change color of background or indicator.

### ISSUE THREAD

**Issue by Hassanmsaid** [kokohuang/flutter_easyloading#77]
I am using this code to customize the style of the loader:
```
EasyLoading.instance
      ..displayDuration = const Duration(milliseconds: 2000)
      ..indicatorType = EasyLoadingIndicatorType.fadingCircle
      ..loadingStyle = EasyLoadingStyle.dark
      ..indicatorSize = 60
      ..radius = 20
      ..backgroundColor = Colors.green
      ..indicatorColor = Colors.yellow
      ..maskColor = kColorDarkGreen.withOpacity(0.5)
      ..userInteractions = true
      ..dismissOnTap = false
      ..indicatorType = EasyLoadingIndicatorType.doubleBounce;
```
Result: Everything works fine except for indicator and background colors, they don't change.

And when I use:
```
..loadingStyle = EasyLoadingStyle.custom
```
The loader doesn't even show.

The way I call:
```
 EasyLoading.show();
```

**Comment by kokohuang** [comment]
@Hassanmsaid Hi, when you set `loadingStyle ` to `EasyLoadingStyle.custom`, the `textColor` should not be null

https://github.com/kokohuang/flutter_easyloading/blob/bc94c563800ac617067119f2a59bbd73aaac5505/lib/src/easy_loading.dart#L429

**Comment by Hassanmsaid** [comment]
Thank you @kokohuang! 🙏🏻 I added textColor and indicatorColor and it worked as they are both mandatory.

**Comment by kokohuang** [comment]
@Hassanmsaid Glad to help
