### ISSUE TITLE
show 方法使用发现的问题

### ISSUE THREAD

**Issue by addappcn** [kokohuang/flutter_easyloading#78]
EasyLoading.show(status: 'loading...',dismissOnTap: false,maskType: EasyLoadingMaskType.clear);
1.全局配置 没有任何作用
2.EasyLoadingMaskType.clear or black  loading的时候还是能交互

**Comment by kokohuang** [comment]
@addappcn 看下全局配置`userInteractions`是否为 `true`

**Comment by HeyuanXie** [comment]
![Uploading 截屏2021-02-07 下午4.54.37.png…]()

网络请求开始时show了一个，请求结果返回dismiss了。如果有错误有会再showToast，为什么showToast没有效果呢

**Comment by kokohuang** [comment]
@HeyuanXie 可以先打断点看下调用顺序
