### ISSUE TITLE
animationStyle is missing in easyloading.

### ISSUE THREAD

**Issue by Oliverq755** [kokohuang/flutter_easyloading#79]
**Describe the bug**
animationStyle is missing in the EasyLoading instance. 

**Flutter/Dart info**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_GB.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[!] Android Studio (not installed)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Screenshots**
![Screenshot from 2020-12-30 13-29-03](https://user-images.githubusercontent.com/34798266/103338034-19ecb500-4aa3-11eb-9e8f-61ece51d5ffe.png)

**Comment by kokohuang** [comment]
@Oliverq755 Hi, you can global set `animationStyle` like this:
`EasyLoading.instance.animationStyle = EasyLoadingAnimationStyle.opacity;`

**Comment by Oliverq755** [comment]
using ```EasyLoading.instance.animationStyle = EasyLoadingAnimationStyle.opacity;``` is not affecting anything on animation style. I would recommend providing the code sample for the demo screen
