### ISSUE TITLE
shoToast 和 showLoading 背景分别自定义

### ISSUE THREAD

**Issue by xiangxm** [kokohuang/flutter_easyloading#80]
**Describe the Feature request**
使用EasyLoading ，想在loading弹窗使用透明背景，只显示Loading的动画，toast的时候想加一个半透明背景，作为toast消息的框，目前不能单独分开设置

**Comment by kokohuang** [comment]
@xiangxm 目前可以在` show` 的时候分别传入 `maskType` 参数
