### ISSUE TITLE
在WidgetsBinding.instance.addPostFrameCallback(() {}) 中添加EasyLoading.show();报错提示： Duplicate GlobalKey detected in widget tree.

### ISSUE THREAD

**Issue by 2673542667** [kokohuang/flutter_easyloading#81]
如题，当我在initState中添加WidgetsBinding.instance.addPostFrameCallback回调函数里面使用 EasyLoading.show();便报错

![image](https://user-images.githubusercontent.com/27001255/103391535-ee2a0780-4b54-11eb-8eb9-be0ed567ca71.png)

![image](https://user-images.githubusercontent.com/27001255/103391518-dd799180-4b54-11eb-9375-a8b476ffb992.png)

请大佬帮我指点一下，是我使用的方式不对吗？

**Comment by kokohuang** [comment]
@2673542667 `initState ` 中可直接使用 `EasyLoading`，去掉 `WidgetsBinding.instance.addPostFrameCallback(() {})` 试试

**Comment by 2673542667** [comment]
> @2673542667 `initState ` 中可直接使用 `EasyLoading`，去掉 `WidgetsBinding.instance.addPostFrameCallback(() {})` 试试

好的，我试一试

**Comment by 2673542667** [comment]
> @2673542667 `initState ` 中可直接使用 `EasyLoading`，去掉 `WidgetsBinding.instance.addPostFrameCallback(() {})` 试试

![image](https://user-images.githubusercontent.com/27001255/103391748-edde3c00-4b55-11eb-808b-20de09fd04d6.png)

![image](https://user-images.githubusercontent.com/27001255/103391738-e3bc3d80-4b55-11eb-9ccb-27b685ea1202.png)

您好，还是一样的

**Comment by kokohuang** [comment]
看报错原因，是因为你的 `GlobalKey` 重复使用了

**Comment by 2673542667** [comment]
> 看报错原因，是因为你的 `GlobalKey` 重复使用了

对，但是我并没有定义`GlobalKey `，然后我尝试把initState中EasyLoading.show();的有关方法注释后，就不会有问题了

**Comment by kokohuang** [comment]
@2673542667 可否提供一个可复现的 `demo`，我再看看

**Comment by 2673542667** [comment]
> @2673542667 可否提供一个可复现的 `demo`，我再看看
> 
> example 里面直接使用是没问题的
> 
> https://github.com/kokohuang/flutter_easyloading/blob/bc6eee86894ba6b24c793e20f36efa2ac46fd6fc/example/lib/test.dart#L12-L17

demo有点儿麻烦，我是这个样子使用的，我在最顶层的组件用FlutterEasyLoading(child:  Subcomponents())包裹了一些字组件，然后在子组件中没有使用FlutterEasyLoading()包裹，直接调用相关方法，如下图：

![image](https://user-images.githubusercontent.com/27001255/103392793-7c54bc80-4b5a-11eb-8b59-3744407a5b68.png)

![image](https://user-images.githubusercontent.com/27001255/103392856-b756f000-4b5a-11eb-9940-b5f96a280b70.png)

![image](https://user-images.githubusercontent.com/27001255/103392934-19175a00-4b5b-11eb-8f8a-1675f9e97165.png)

**Comment by kokohuang** [comment]
@2673542667 初始化方式调整下，你只需要在 `MaterialApp` 的 `builder` 参数传入 `EasyLoading.init()` 就行，即可在全局任意地方使用，不需要使用 `FlutterEasyLoading ` 包裹

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: EasyLoading.init(),
    );
  }
}
```

**Comment by 2673542667** [comment]
> @2673542667 初始化方式调整下，你只需要在 `MaterialApp` 的 `builder` 参数传入 `EasyLoading.init()` 就行，即可在全局任意地方使用，不需要使用 `FlutterEasyLoading ` 包裹
> 
> ```dart
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter EasyLoading',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter EasyLoading'),
>       builder: EasyLoading.init(),
>     );
>   }
> }
> ```

好的，我试一试

**Comment by 2673542667** [comment]
> @2673542667 初始化方式调整下，你只需要在 `MaterialApp` 的 `builder` 参数传入 `EasyLoading.init()` 就行，即可在全局任意地方使用，不需要使用 `FlutterEasyLoading ` 包裹
> 
> ```dart
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter EasyLoading',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter EasyLoading'),
>       builder: EasyLoading.init(),
>     );
>   }
> }
> ```

问题已经解决，换成这种可以，感谢大佬🙏
