### ISSUE TITLE
已经使用MediaQuery时，builder如何初使化

### ISSUE THREAD

**Issue by albertbxl** [kokohuang/flutter_easyloading#83]
> 
            builder: (context, widget) {
              return MediaQuery(
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                child: widget,
              );
            },

如何初使化EasyLoading.init()

**Comment by kokohuang** [comment]
@albertbxl 

```dart
      builder: EasyLoading.init(builder: (context, widget) {
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
          child: widget,
        );
      }),
```

**Comment by albertbxl** [comment]
完美解决，感谢！

**Comment by zgayjjf** [comment]
Please add this usage to the docs. 😄 
I think this is a common questions.
