### ISSUE TITLE
overlayEntry should not be null

### ISSUE THREAD

**Issue by stoppiNeobiz** [kokohuang/flutter_easyloading#84]
**Describe the bug**
I receive an error from flutter 
`[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter_easyloading/src/easy_loading.dart': Failed assertion: line 428 pos 7: 'overlayEntry != null': overlayEntry should not be null`

**Flutter/Dart info**
please run `flutter doctor` then put it here.

**Screenshots**

**Comment by kokohuang** [comment]
@stoppiNeobiz 

Initialize EasyLoading in your `MaterialApp`

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: EasyLoading.init(),
    );
  }
}
```

**Comment by BartusZak** [comment]
@kokohuang how can I do that with more advanced build configuration?

```dart
 @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      key: _navigatorKey,
      title: 'Title',
      theme: ThemeData(
        primarySwatch: Colors.grey,
        appBarTheme: AppBarTheme(
          color: Colors.white,
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      builder: (context, child) {
        ErrorWidget.builder = (FlutterErrorDetails errorDetails) {
          return buildError(context, errorDetails);
        };

        EasyLoading.init(); // does not work

        // ignore: close_sinks
        final ApplicationBloc _applicationBloc =
            BlocProvider.of<ApplicationBloc>(context);

        return Container(
          child: BlocProvider(
            create: (_) => _applicationBloc,
            child: BlocListener<ApplicationBloc, ApplicationState>(
              listener: _applicationBlocListener,
              child: BlocBuilder<ApplicationBloc, ApplicationState>(
                builder: (context, state) {
                  if (state is InitialApplicationState ||
                      state is ApplicationLoadingState) {
                    return LoadingWidget();
                  } else if (state is ApplicationLoadedState) {
                    return child;
                  } else {
                    return Text("Application load error. Try again.");
                  }
                },
              ),
            ),
          ),
        );
      },
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const <Locale>[
        const Locale('en', 'US'),
        const Locale('pl', 'PL'),
      ],
      routerDelegate: _appRouter.delegate(),
      routeInformationParser: _appRouter.defaultRouteParser(),
    );
  }
```

**Comment by kokohuang** [comment]
EasyLoading.init() 

> @kokohuang how can I do that with more advanced `builder` configuration?
> 
> ```dart
>  @override
>   Widget build(BuildContext context) {
>     return MaterialApp.router(
>       debugShowCheckedModeBanner: false,
>       key: _navigatorKey,
>       title: 'Title',
>       theme: ThemeData(
>         primarySwatch: Colors.grey,
>         appBarTheme: AppBarTheme(
>           color: Colors.white,
>         ),
>         visualDensity: VisualDensity.adaptivePlatformDensity,
>       ),
>       builder: (context, child) {
>         ErrorWidget.builder = (FlutterErrorDetails errorDetails) {
>           return buildError(context, errorDetails);
>         };
> 
>         EasyLoading.init(); // does not work
> 
>         // ignore: close_sinks
>         final ApplicationBloc _applicationBloc =
>             BlocProvider.of<ApplicationBloc>(context);
> 
>         return Container(
>           child: BlocProvider(
>             create: (_) => _applicationBloc,
>             child: BlocListener<ApplicationBloc, ApplicationState>(
>               listener: _applicationBlocListener,
>               child: BlocBuilder<ApplicationBloc, ApplicationState>(
>                 builder: (context, state) {
>                   if (state is InitialApplicationState ||
>                       state is ApplicationLoadingState) {
>                     return LoadingWidget();
>                   } else if (state is ApplicationLoadedState) {
>                     return child;
>                   } else {
>                     return Text("Application load error. Try again.");
>                   }
>                 },
>               ),
>             ),
>           ),
>         );
>       },
>       localizationsDelegates: [
>         GlobalMaterialLocalizations.delegate,
>         GlobalWidgetsLocalizations.delegate,
>         GlobalCupertinoLocalizations.delegate,
>       ],
>       supportedLocales: const <Locale>[
>         const Locale('en', 'US'),
>         const Locale('pl', 'PL'),
>       ],
>       routerDelegate: _appRouter.delegate(),
>       routeInformationParser: _appRouter.defaultRouteParser(),
>     );
>   }
> ```

https://github.com/kokohuang/flutter_easyloading/issues/83#issuecomment-754470520

**Comment by kyadakrupali08** [comment]
I was got this errer Please help me ASAP

'package:flutter_easyloading/src/easy_loading.dart': Failed assertion: line 298 pos 7: '_getInstance().overlayEntry != null': overlayEntry should not be null

This is my Flutter Doctor details

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.14393], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 4.1.0)
[√] Connected device (1 available)

**Comment by kokohuang** [comment]
@kyadakrupali08 you shuld init EasyLoading in you MaterialApp

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: EasyLoading.init(),
    );
  }
}
```
