### ISSUE TITLE
请问MyApp类，build之前我想使用弹出转圈怎么处理啊。

### ISSUE THREAD

**Issue by xinlee333** [kokohuang/flutter_easyloading#87]
在MaterialApp里的builder参数添加EasyLoading.init()是标准做法。
但是我想在_MyAppState的initState函数里做一些初始化处理，如果有问题，我需要弹出提示，但是在这个函数里调用就会报错，这个怎么处理啊？因为还没有执行到EasyLoadinglinit()

  @override
  void initState() {
    super.initState();
    EasyLoading.show(.....省略...)
 }

**Comment by kokohuang** [comment]
@xinlee333 暂时没办法处理这种场景
