### ISSUE TITLE
请问 多个 builder怎么配置？初始化builder的位置有其他初始化了

### ISSUE THREAD

**Issue by JGNS** [kokohuang/flutter_easyloading#89]
**Describe the bug**

**Flutter/Dart info**
please run `flutter doctor` then put it here.

**Screenshots**

**Comment by JGNS** [comment]
![image](https://user-images.githubusercontent.com/31919344/110309843-ce273080-803c-11eb-92db-4fec879c70c6.png)
我知道怎么做了，谢谢，这种方式不用init（），测试可以正常运行

**Comment by kokohuang** [comment]
@JGNS 你这种初始化方法有问题的，全局只需要初始化一次就行

参考：
https://github.com/kokohuang/flutter_easyloading/issues/83#issuecomment-754470520
