### ISSUE TITLE
when i add EasyLoading.init(),  there comes the problem

### ISSUE THREAD

**Issue by yexiang1994** [kokohuang/flutter_easyloading#90]
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 552 pos 15: 'textDirection != null': is not true.

The following assertion was thrown building Overlay(state: OverlayState#36d0c(entries: [EasyLoadingOverlayEntry#24312(opaque: false; maintainState: false), EasyLoadingOverlayEntry#a4571(opaque: false; maintainState: false)])):

what should ido

**Comment by kokohuang** [comment]
@yexiang1994 show you code please...


```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: EasyLoading.init(),
    );
  }
}
```

**Comment by yexiang1994** [comment]
thanks. i fixed it,
