### ISSUE TITLE
EasyLoading.show(status:" Loading")

### ISSUE THREAD

**Issue by longfit** [kokohuang/flutter_easyloading#92]
我把 test instate()  內  Easyloading.showSucess(...) 成 EasyLoading.show(...)
不會在幾消去..

怎樣 使用 EasyLoading.dismiss 當完成 return table build widget

**Comment by kokohuang** [comment]
如果只是想监听 build 结束就隐藏的话可以这样写：

```dart
WidgetsBinding.instance.addPostFrameCallback((_) {
    EasyLoading.dismiss();
});
```

**Comment by longfit** [comment]
謝謝你指引。
因為 想在在 打一個 page 顯示多項 table row data ,
1) 在 inistate()
       EasyLoading.show(status: "P.O ");
    EasyLoading.addStatusCallback(statusCallback);
  ...
void statusCallback(EasyLoadingStatus status) {
    print('Test EasyLoading Status $status');
  }
2) 然放 
WidgetsBinding.instance.addPostFrameCallback((_) {
    EasyLoading.dismiss();
}); 
在 Widget Build....

結果甚麼都沒有

我想在 initstate 讀取 json 資料前 easyloading.show....
完成table 資料顯 示，就 dismiss ..

**Comment by kokohuang** [comment]
@longfit 那你可以在读取json数据之后调用 EasyLoading.dismiss();
