### ISSUE TITLE
dismissOnTap: true , has no effect

### ISSUE THREAD

**Issue by guyulmaz** [kokohuang/flutter_easyloading#94]
**Describe the bug**
flutter_easyloading: ^3.0.0

EasyLoading.showToast(mesaj,
      toastPosition: EasyLoadingToastPosition.center,
      dismissOnTap: true,
      duration: Duration(seconds: 5));

but toast is disappearing without requesting any tap.

**Flutter/Dart info**
please run `flutter doctor` then put it here.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)   
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (3 available)

• No issues found!

**Screenshots**

**Comment by kokohuang** [comment]
@guyulmaz `dismissOnTap` is meaning that when toast is showing and will dismiss with tap on screen

**Comment by guyulmaz** [comment]
the problem without making any tap on the screen, toast is disappearing

**Comment by kokohuang** [comment]
when you set `duration: Duration(seconds: 5)`, toast will dissmiss after 5 seconds.
you mean, toast disappeared before 5 seconds?

**Comment by guyulmaz** [comment]
EasyLoading.showToast(
    mesaj,
    toastPosition: EasyLoadingToastPosition.center,
    dismissOnTap: true,
    //duration: Duration(seconds: 5)
  );
toast disappear without any tap even dismissOnTap: true

**Comment by kokohuang** [comment]
@guyulmaz okay, what you want is that you wish Toast will be always showing until call `EasyLoading.dismiss()`?

**Comment by guyulmaz** [comment]
Toast will be always showing until user taps
isn't dismissOnTap: true is for this, why is it not working?

**Comment by kokohuang** [comment]
`dismissOnTap: true` is meaing that when toast/loading is showing,  toast/loading will dismiss immediately on user tap...

**Comment by guyulmaz** [comment]
yes problem is it dismiss without any user tap

**Comment by kokohuang** [comment]
you can keep toast always showing by set duration with large value...
