### ISSUE TITLE
EasyLoading.init(); not working

### ISSUE THREAD

**Issue by Umar-Khan-Yousafzai** [kokohuang/flutter_easyloading#98]
### Hello There

So my problem is that I am using Responsive Framework and it is already on builder in Material App.

I realized that if I remove lambda and make my builder function with the body I can add   **EasyLoading.init();** in the _**builder function**_ as you can see in the code.

But when I use the application and I used it in side my other file I get following error:

`**_[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter_easyloading/src/easy_loading.dart': Failed assertion: line 422 pos 7: 'overlayEntry != null': You should call EasyLoading.init() in your MaterialApp_**`

So Is there any way I can use it another way?
**```

    return MaterialApp(

      locale: _locale,
      builder: (context, widget) {
        EasyLoading.init();
        return ResponsiveWrapper.builder(
          BouncingScrollWrapper.builder(context, widget),
          maxWidth: 1200,
          minWidth: 400,
          defaultScale: true,
          breakpoints: [
            ResponsiveBreakpoint.resize(400, name: 'Low Mobile'),
            ResponsiveBreakpoint.resize(600, name: MOBILE),
            ResponsiveBreakpoint.autoScale(800, name: TABLET),
            ResponsiveBreakpoint.autoScale(1200, name: DESKTOP)
          ]) ;
```**

**Comment by kokohuang** [comment]
#83 @Umar-Khan-Yousafzai
