### ISSUE TITLE
覆盖了背景图

### ISSUE THREAD

**Issue by 673697831** [kokohuang/flutter_easyloading#99]
@override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage("images/ic_new_vod_bg.png"),
            fit: BoxFit.cover,
          )
      ),
      child: MaterialApp(
          home: Scaffold(
            backgroundColor: Colors.transparent,
            appBar: AppBar(
              backgroundColor: Colors.transparent,
              title: const Text('', style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),),
            ),
            body: Builder(
                builder: (context) {
                  return Container(
                    color: Colors.transparent,
                    child: TreePage(),
                  );
                }
            ),
          ),
        builder: EasyLoading.init(),
      ),
    );
  }
DecorationImage出现异常

**Comment by kokohuang** [comment]
`MaterialApp ` 全局只有一个。。。。在 `mian.dart` 里面

**Comment by 673697831** [comment]
我就是main.dart里面设置

**Comment by kokohuang** [comment]
你把 MaterialApp 放最外层

**Comment by xtuck** [comment]
请问你解决了吗？我也遇到了同样的问题

**Comment by ijoywan** [comment]
you can set   canvasColor of ThemeData  like

```
theme: ThemeData(
              canvasColor: Colors.transparent
)
```

you must set it in `lib/main.dart`
